services:
  - type: web
    name: fastapi
    runtime: docker
    plan: free
    region: frankfurt
    branch: maingit add
    envVars:
      - key: MONGO_URL
        sync: false
    buildFilter:
      paths:
        - app/**
